import "./globals.css";
import ToasterContext from "@/Context/ToasterContext";
import AuthProvider from "@/Context/AuthContext";

export const metadata = {
  title: "TWitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToasterContext />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
